name: push demo example
on:
  pull_request:
    types: [opened] #activity types
  workflow_dispatch: # second event
  push:
    branches:
      - main
      - 'dev-*'  # any branch starting with dev
      - 'feat/**' # feat/2025/branch
    paths:
      - '**.js' # when files changes  of type js
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci 
      - name: Run lint
        run: npm run lint