name: Run tests
on: push
jobs:
  test: #job name custom
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with: # provides config for action use
          node-version: 18
      - name: Install dependecies
        run: npm ci
      - name: RUn tests
        run: npm test
  deploy: 
    needs: test # job name it depends on
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with: # provides config for action use
          node-version: 18
      - name: Install dependecies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying"
       