name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output github context
        run: echo "${{ toJSON(github) }}" #  meta data
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name : Cache dependency
        uses: actions/cache@v3
        with:
          path: ~/.npm # npm created cache
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}} # retrive cache values
      - name: Install dependecies
        run: npm ci 
      - name: Run lint
        run: npm run lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    outputs: # variables to share with other jobs
      script-file: ${{ steps.publish.outputs.script-file}}  # id of step i.e publish given
    steps:    
      - name: Get code
        uses: actions/checkout@v3
      - name : Cache dependency
        uses: actions/cache@v3
        with:
          path: ~/.npm # npm created cache
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}} # retrive cache values
      - name: Install dependecies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Publish JS file name
        id : publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'  #$GITHUB_OUTPUT --> to communicate data b/w steps within same job
      - name: Upload artificats
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Build artrifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files # same as artifact step name
      - name : output contents
        run : ls
      - name: Output Name
        run: echo "${{needs.build.outputs.script-file}}" #needs contains output jobs
      - name: Deploy
        run: echo "Deploying"